[mqtt]
    host = "tcp://127.0.0.1:1883"
    user = "YO"
    password = "PO"
    topic = "#"
[influx]
    host = "http://localhost:8086"
    user = "muh"
    password = "fnord"
    database = "mydb"
    interval = 5    # in seconds
[[sync]]
    pattern = "foo\\/bar\\/(?P<SENSOR_ID>\\w+)\\/\\w+"
    measurement = "yolo"
[[sync]]
    pattern = "muh\\/baz\\/(?P<SENSOR_ID>\\w+)\\/loom\\/\\w+"
    measurement = "yolo"
